"""Cross-validate Python AOA against R CAST (AC-14).

Requires: src/aoa/tests/fixtures/cast_reference.json
Generated by: Rscript src/aoa/tests/fixtures/generate_cast_fixtures.R
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
from numpy.testing import assert_allclose

from src.aoa import core

FIXTURES_DIR = Path(__file__).parent / "fixtures"
CAST_REF = FIXTURES_DIR / "cast_reference.json"


def _load_cast_fixtures() -> dict:
    """Load R CAST reference values."""
    with open(CAST_REF) as f:
        return json.load(f)


@pytest.fixture
def cast_fixtures():
    if not CAST_REF.exists():
        pytest.skip("R CAST fixtures not generated yet — run generate_cast_fixtures.R")
    return _load_cast_fixtures()


class TestCastComparison:
    """Compare Python AOA core against R CAST trainDI/aoa outputs."""

    def test_standardization_matches(self, cast_fixtures):
        """Python z-score (ddof=1) should match R scale()."""
        X = np.column_stack([cast_fixtures["X_train"][f] for f in cast_fixtures["feature_names"]])
        means = X.mean(axis=0)
        stds = X.std(axis=0, ddof=1)
        assert_allclose(means, cast_fixtures["feature_means"], atol=1e-12)
        assert_allclose(stds, cast_fixtures["feature_stds"], atol=1e-12)

    def test_d_bar_matches(self, cast_fixtures):
        """Python d_bar should match CAST trainDist_avrgMean."""
        X = np.column_stack([cast_fixtures["X_train"][f] for f in cast_fixtures["feature_names"]])
        weights = np.array(cast_fixtures["weights"])
        means = np.array(cast_fixtures["feature_means"])
        stds = np.array(cast_fixtures["feature_stds"])

        X_s = core.standardize_features(X, means, stds)
        X_sw = core.apply_importance_weights(X_s, weights)
        d_bar = core.compute_d_bar_full(X_sw)

        assert_allclose(d_bar, cast_fixtures["d_bar"], atol=1e-10, err_msg="d_bar mismatch between Python and R CAST")

    def test_training_di_matches(self, cast_fixtures):
        """Python training DI should match CAST trainDI."""
        X = np.column_stack([cast_fixtures["X_train"][f] for f in cast_fixtures["feature_names"]])
        weights = np.array(cast_fixtures["weights"])
        means = np.array(cast_fixtures["feature_means"])
        stds = np.array(cast_fixtures["feature_stds"])
        fold_labels = np.array(cast_fixtures["fold_labels"])

        X_s = core.standardize_features(X, means, stds)
        X_sw = core.apply_importance_weights(X_s, weights)
        d_bar = core.compute_d_bar_full(X_sw)
        training_di = core.compute_training_di(X_sw, fold_labels, d_bar)

        expected = np.array(cast_fixtures["training_di"])
        assert_allclose(training_di, expected, atol=1e-10, err_msg="Training DI mismatch between Python and R CAST")

    def test_threshold_matches(self, cast_fixtures):
        """Python threshold should be close to CAST threshold.

        Known difference: our threshold = max(DI[DI <= whisker]) per
        Meyer & Pebesma (2021), while CAST uses the whisker value
        (Q75 + 1.5*IQR) directly. Our value is always <= CAST's.
        We verify both that our threshold <= CAST's and the whisker matches.
        """
        X = np.column_stack([cast_fixtures["X_train"][f] for f in cast_fixtures["feature_names"]])
        weights = np.array(cast_fixtures["weights"])
        means = np.array(cast_fixtures["feature_means"])
        stds = np.array(cast_fixtures["feature_stds"])
        fold_labels = np.array(cast_fixtures["fold_labels"])

        X_s = core.standardize_features(X, means, stds)
        X_sw = core.apply_importance_weights(X_s, weights)
        d_bar = core.compute_d_bar_full(X_sw)
        training_di = core.compute_training_di(X_sw, fold_labels, d_bar)
        threshold = core.compute_threshold(training_di)

        # Our threshold <= CAST threshold (we take max observed, they take whisker)
        assert threshold <= cast_fixtures["threshold"] + 1e-10

        # The whisker formula itself matches exactly
        q25, q75 = np.percentile(training_di, [25, 75])
        whisker = q75 + 1.5 * (q75 - q25)
        assert_allclose(
            whisker,
            cast_fixtures["threshold"],
            atol=1e-10,
            err_msg="Whisker formula mismatch between Python and R CAST",
        )

    def test_prediction_di_matches(self, cast_fixtures):
        """Python prediction DI should match CAST aoa() DI."""
        X = np.column_stack([cast_fixtures["X_train"][f] for f in cast_fixtures["feature_names"]])
        X_new = np.column_stack([cast_fixtures["X_new"][f] for f in cast_fixtures["feature_names"]])
        weights = np.array(cast_fixtures["weights"])
        means = np.array(cast_fixtures["feature_means"])
        stds = np.array(cast_fixtures["feature_stds"])

        X_s = core.standardize_features(X, means, stds)
        X_sw = core.apply_importance_weights(X_s, weights)
        d_bar = core.compute_d_bar_full(X_sw)
        tree = core.build_kdtree(X_sw)

        X_new_s = core.standardize_features(X_new, means, stds)
        X_new_sw = core.apply_importance_weights(X_new_s, weights)
        pred_di = core.compute_prediction_di(X_new_sw, tree, d_bar)

        expected = np.array(cast_fixtures["prediction_di"])
        assert_allclose(pred_di, expected, atol=1e-10, err_msg="Prediction DI mismatch between Python and R CAST")

    def test_aoa_mask_matches(self, cast_fixtures):
        """Python AOA mask should match CAST aoa() AOA field."""
        X = np.column_stack([cast_fixtures["X_train"][f] for f in cast_fixtures["feature_names"]])
        X_new = np.column_stack([cast_fixtures["X_new"][f] for f in cast_fixtures["feature_names"]])
        weights = np.array(cast_fixtures["weights"])
        means = np.array(cast_fixtures["feature_means"])
        stds = np.array(cast_fixtures["feature_stds"])
        fold_labels = np.array(cast_fixtures["fold_labels"])

        X_s = core.standardize_features(X, means, stds)
        X_sw = core.apply_importance_weights(X_s, weights)
        d_bar = core.compute_d_bar_full(X_sw)
        training_di = core.compute_training_di(X_sw, fold_labels, d_bar)
        threshold = core.compute_threshold(training_di)
        tree = core.build_kdtree(X_sw)

        X_new_s = core.standardize_features(X_new, means, stds)
        X_new_sw = core.apply_importance_weights(X_new_s, weights)
        pred_di = core.compute_prediction_di(X_new_sw, tree, d_bar)
        aoa_mask = pred_di <= threshold

        expected = np.array(cast_fixtures["prediction_aoa"])
        np.testing.assert_array_equal(aoa_mask, expected, err_msg="AOA mask mismatch between Python and R CAST")
